baseURL = 'https://zzoyu.github.io/blog/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'ko-KR'
defaultContentLanguage = 'ko'
theme = 'enchanted-lowkey'
title = 'Call me Ishmael.'
enableRobotsTXT = true
summaryLength = 15
pagination.pagerSize = 5


[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'